<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--多模块Pom管理:https://www.cnblogs.com/ElEGenT/p/12938773.html-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.0</version>
    </parent>

    <groupId>org.kitona</groupId>
    <artifactId>zus</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>zus</name>
    <description>zus: Java项目的脚手架</description>


    <properties>
        <revision>1.0.0-SNAPSHOT</revision>

        <java.version>17</java.version>
        <maven.version>3.8.1</maven.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!--多模块pom管理插件-->
        <flatten-maven-plugin.version>1.7.0</flatten-maven-plugin.version>
        <!--脚手架插件-->
        <maven-archetype-plugin.version>3.4.1</maven-archetype-plugin.version>

        <spring-boot.version>3.3.0</spring-boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <lombok.version>1.18.40</lombok.version>
        <orika.version>1.5.4</orika.version>
        <commons-lang3.version>3.19.0</commons-lang3.version>
        <fastjson.version>2.0.35</fastjson.version>
        <hibernate-validator.version>8.0.0.Final</hibernate-validator.version>
    </properties>

    <modules>
        <module>zus-starter</module>
        <module>zus-api</module>
        <module>zus-business</module>
        <module>zus-service</module>
        <module>zus-facade</module>
        <module>zus-client</module>
        <module>zus-common</module>
        <module>zus-infrastructure</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!--====================== 项目内部模块 Start======================-->
            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-starter</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-api</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-business</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-service</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-facade</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-client</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-infrastructure</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.kitona</groupId>
                <artifactId>zus-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <!--====================== 项目内部模块 End======================-->

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--Spring Boot Actuator 模块提供了生产级别的功能，比如健康检查，审计，指标收集，HTTP 跟踪等，帮助我们监控和管理Spring Boot 应用。-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-actuator</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>

            <!--Spring Boot Validation 模块提供了对 Java Bean Validation API 的支持，可以帮助我们进行参数校验。-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-validation</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>

            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <scope>runtime</scope>
            </dependency>

            <!--=============外部工具 Start===============-->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <optional>true</optional>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate-validator.version}</version>
            </dependency>

            <dependency>
                <groupId>ma.glasnost.orika</groupId>
                <artifactId>orika-core</artifactId>
                <version>${orika.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <!--=============外部工具 End===============-->

            <!--============测试相关依赖 Start================-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${spring-boot.version}</version>
                <scope>test</scope>
            </dependency>
            <!--============测试相关依赖 End================-->
        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!--多模块pom管理插件-->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <!--resolveCiFriendliesOnly 模式只解析特定的 CI 友好变量（如 ${revision}, ${sha1}, ${changelist}），但不会解析普通的 Maven 属性。-->
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--脚手架生成插件-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-archetype-plugin</artifactId>
                <version>${maven-archetype-plugin.version}</version>
                <configuration>
                    <propertyFile>archetype.properties</propertyFile>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
