<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.kitona</groupId>
        <artifactId>zus</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>zus-business</artifactId>
    <name>zus-business</name>
    <description>zus-business:业务所在的聚合层,基于Service提供的能力执行业务聚合</description>

    <dependencies>
        <dependency>
            <groupId>org.kitona</groupId>
            <artifactId>zus-service</artifactId>
        </dependency>

        <dependency>
            <groupId>org.kitona</groupId>
            <artifactId>zus-facade</artifactId>
        </dependency>

        <dependency>
            <groupId>org.kitona</groupId>
            <artifactId>zus-client</artifactId>
        </dependency>

        <dependency>
            <groupId>org.kitona</groupId>
            <artifactId>zus-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
        </dependency>
    </dependencies>
</project>
