<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.kitona</groupId>
        <artifactId>zus</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>zus-client</artifactId>
    <name>zus-client</name>
    <description>zus-client: 二方包(SDK) - 对外发布的 RPC 接口定义和 DTO，供其他微服务依赖调用，独立版本管理</description>

    <dependencies>
        <dependency>
            <groupId>org.kitona</groupId>
            <artifactId>zus-common</artifactId>
        </dependency>
    </dependencies>
</project>
